version: '3.7'

networks:
  kafka-net:

services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_DB=midas
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=midas
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "25432:5432"


  zookeeper:
    image: zookeeper:3.6.3
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "19093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "generate-otp-topic:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:19093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    networks:
      - kafka-net